version: '3.8'

services:
  # NestJS Application
  nestjs-app:
    container_name: nestjs-app
    build:
      context: . # Path to your NestJS project Dockerfile
      target: development  # Use the development stage for local development
    ports:
      - "3000:3000" # Expose NestJS app port
    depends_on:
      - elasticsearch
      - kafka
    volumes:
      - .:/app  # Mount the local directory to enable live reload
      - /app/node_modules  # Ensure node_modules is not overwritten
    environment:
      ELASTICSEARCH_HOST: elasticsearch:9200
    networks:
      - app-network
    command: pnpm start:dev

  # Elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app-network
    logging:
      driver: none

  kafka:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - app-network
    logging:
      driver: none

# Define a custom network for all services
networks:
  app-network:
    driver: bridge

volumes:
  kafka_data:
    driver: local